rockchip documentation
owncast/owncast.github.io pull request #180
Opened 2024-08-11 19:15 UTC by ZiTAL

documentation for rockchip

2024-08-12 23:27 UTC, gabek requested changes

2024-08-12 23:27 UTC, gabek commented on content/docs/codecs.md
> +### Rokchip (h264_rkmpp)
Typo, Rockchip.

2024-08-12 23:27 UTC, gabek commented on content/docs/codecs.md
> +Hardware support for rockchip Socs like Orange Pi 5.
I don't think most people know what the "soc" acronym stands for, so maybe use "chipset"?

2024-08-12 23:27 UTC, gabek commented on content/docs/codecs.md
> +Using that version of the ffmpeg is 5 times faster than software encoding via libx264.
Some detail about this will need to be provided. It should be made super clear that you **must** use an entirely different version of ffmpeg, **and** you have to build it yourself. So it should call out that it requires experience building your own copy of ffmpeg to get this solution to work at all.

2024-08-13 08:12 UTC, ZiTAL commented
write the documentation with your style and standards, maybe jellyfin documentation helps:

https://jellyfin.org/docs/general/administration/hardware-acceleration/rockchip/

2024-08-13 11:18 UTC, ZiTAL commented
I probed this ffmpeg versions of jellyfin, and it works ok with **h264_rkmpp** encoder, no needed to compile it!

https://repo.jellyfin.org/?path=/ffmpeg/debian

2024-08-13 21:18 UTC, gabek commented
> I probed those ffmpeg versions of jellyfin, and it works ok with h264_rkmpp encoder, no needed to compile it!

I guess I don't fully understand. If somebody were to buy an Orange Pi, does the copy of `ffmpeg` that comes with it have `h264_rkmpp` built-in?

2024-08-14 06:08 UTC, ZiTAL commented
> > I probed those ffmpeg versions of jellyfin, and it works ok with h264_rkmpp encoder, no needed to compile it!
> 
> I guess I don't fully understand. If somebody were to buy an Orange Pi, does the copy of `ffmpeg` that comes with it have `h264_rkmpp` built-in?

yes

2024-08-14 14:57 UTC, gabek commented
Got it. Then you probably don't need to point them to the git repo of the source code of `ffmpeg`, because it makes it sound like they have to do something with it. That's what I thought when I read it.

2024-08-14 20:42 UTC, closed without merging