Add systemd installation method
owncast/owncast.github.io pull request #25
Opened 2020-12-28 14:50 UTC by SkYNewZ

https://github.com/owncast/owncast/issues/521

2020-12-28 17:55 UTC, gabek requested changes
I think we just need to find the right place to put this information, that's not in the Quickstart.

2020-12-28 17:55 UTC, gabek commented on content/docs/quickstart.md
> +2. Run `docker run -p 8080:8080 -p 1935:1935 -it gabekangas/owncast:latest` to start the service.
The "1. 1. 1." syntax is used on purpose because Markdown will always increment the numbers.  This is handy if you need to move things around or insert another line, then you don't need to go back and change all the numbers, just let Markdown number them for you.

2020-12-28 17:55 UTC, gabek commented on content/docs/quickstart.md
> +- downloading a zip file of Owncast and run it as systemd unit file
I'm not sure we want to talk about systemd in the Quickstart.  systemd is not required to download and run Owncast and should be treated as optional additional information.  I almost thinks we should have a separate document with things you can learn about after you have Owncast running, like systemd, reverse proxies (for SSL), etc.  But given that none of that has anything to do with actually downloading and running Owncast I don't want to make it sound like there's more steps and tools you have to learn.  What are your thoughts @jeyemwey @gingervitis ?

2020-12-28 20:43 UTC, SkYNewZ commented on content/docs/quickstart.md
> +2. Run `docker run -p 8080:8080 -p 1935:1935 -it gabekangas/owncast:latest` to start the service.
Oh thanks for the tip, I did not know that !

2020-12-28 20:45 UTC, SkYNewZ commented
Okay, thanks for the review. I will wait some updates !

2020-12-28 21:59 UTC, jeyemwey commented on content/docs/quickstart.md
> +- downloading a zip file of Owncast and run it as systemd unit file
I'm certain that we should not put this into our Quickstart guide. Like Gabe said, another page with example configurations for other applications (nginx, apache2, caddy, systemd right here) would be great. Not sure how we could call this, but this PR will be a good start.

2020-12-28 22:04 UTC, jeyemwey approved these changes

2020-12-28 22:04 UTC, jeyemwey commented on content/docs/quickstart.md
> +```bash
Hugo has previously had its problems with this declaration of syntax highlighting.

On other pages, we have used this syntax:

```
{{< highlight /* your language here */ >}}
/* your content here */
{{< / highlight >}}
```

2020-12-28 22:04 UTC, jeyemwey commented on content/docs/quickstart.md
> +```systemd
See my first comment.

2020-12-28 22:04 UTC, jeyemwey commented on content/docs/quickstart.md
> +```bash
See above.

2020-12-28 22:04 UTC, jeyemwey commented on content/docs/quickstart.md
> +```bash
See above.

2020-12-28 22:04 UTC, jeyemwey commented on content/docs/quickstart.md
> +```bash
See above.

2020-12-28 22:05 UTC, jeyemwey requested changes
Not what I wanted. See my comments above. >:(

2020-12-29 10:25 UTC, SkYNewZ commented on content/docs/quickstart.md
> +- downloading a zip file of Owncast and run it as systemd unit file
I understand and agree with that. Indeed, "quick start" is no longer as "quick" and easy to handle with this... What do you think about a "Post-install" section ?

2020-12-29 10:30 UTC, jeyemwey requested changes
One more thing!

2020-12-29 10:30 UTC, jeyemwey commented on content/docs/quickstart.md
> +1. Install [`ffmpeg`](https://ffmpeg.org/download.html) if you haven't.  Use version 1.1.5 or above.
Possible search and replace error, ffmpeg 4.1.5 is still correct.

2020-12-29 10:38 UTC, SkYNewZ commented on content/docs/quickstart.md
> +1. Install [`ffmpeg`](https://ffmpeg.org/download.html) if you haven't.  Use version 1.1.5 or above.
Oh yes, sorry...

2020-12-29 10:43 UTC, SkYNewZ commented
I have pushed an idea for a post-installation section

2020-12-30 21:10 UTC, jeyemwey commented
Thanks for your effort, great stuff!

I'm not sure if "Post-install" is the right title for this page. Maybe "Intergrating Owncast" or "System Integrations"? Additionally, a little helper text would be helpful:

> After getting Owncast, you can integrate it in your existing server infrastructure. This page will help you, if you want to use Owncast with a Reverse proxy or run it with systemd. If you have integrated Owncast with another service, please add your findings with the "Edit" button at the very bottom.

Also, since the Caddy documentation is not part of this issue, I would like to not publish it at this point.

Another thing: You can add several commits to a PR and don't need to force-push it again and again.

2021-01-01 22:22 UTC, kaffeeringe reviewed
I can't get to start owncast as service with this manual. When I start it and look at the status it seems to fail:

`owncast.service: Failed with result 'exit-code'.
`
When I try and start owncast /var/www/vhosts/MYPATH/owncast it tells me, there's no config.yaml. I bet it has something to do with the "WorkingDirectory" - but that is copied the same path...

2021-01-02 09:25 UTC, gabek commented
> I can't get to start owncast as service with this manual. When I start it and look at the status it seems to fail:
> 
> `owncast.service: Failed with result 'exit-code'. `
> When I try and start owncast /var/www/vhosts/MYPATH/owncast it tells me, there's no config.yaml. I bet it has something to do with the "WorkingDirectory" - but that is copied the same path...

You can specify the path to the config file, if that's possibly the issue, with the `--configFile` flag:

`/var/www/vhosts/MYPATH/owncast --configFile /var/www/vhosts/MYPATH/config.yaml`

Not sure if it'll help, but something to try.

2021-01-02 11:22 UTC, kaffeeringe commented
It now exits with "code=exited, status=203/EXECT"

"The actual process execution failed (specifically, the execve(2) system call). Most likely this is caused by a missing or non-accessible executable file."

Is it possible, that the service can't access the files? I changed ownership to the owncast-user as suggested.

2021-01-03 13:56 UTC, SkYNewZ commented
> 
> 
> > I can't get to start owncast as service with this manual. When I start it and look at the status it seems to fail:
> > `owncast.service: Failed with result 'exit-code'. `
> > When I try and start owncast /var/www/vhosts/MYPATH/owncast it tells me, there's no config.yaml. I bet it has something to do with the "WorkingDirectory" - but that is copied the same path...
> 
> You can specify the path to the config file, if that's possibly the issue, with the `--configFile` flag:
> 
> `/var/www/vhosts/MYPATH/owncast --configFile /var/www/vhosts/MYPATH/config.yaml`
> 
> Not sure if it'll help, but something to try.

On my own, I don't use the `--configFile` flag because `WorkingDirectory` should do the job **and** Owncast serves static files (all the HTML part etc) from its relative path no?

- `WorkingDirectory` must be the Owncast directory (e.g. `/var/www/vhosts/MYPATH`).
- `ExecStart` must be the Owncast directory ending with `/owncast`, the `owncast` binary (e.g. `/var/www/vhosts/MYPATH/owncast`).

But I supposed you already done that... 🤔
Does the `owncast` user have good access to `/var/www/vhosts/MYPATH` and all this content?

2021-01-03 16:29 UTC, kaffeeringe commented
@SkYNewZ - Yes it works now. The problem was, that the user owncast wasn't allowed to access the whole path. I had to 755 /var - then it worked fine.

2021-01-03 16:44 UTC, SkYNewZ commented
> @SkYNewZ - Yes it works now. The problem was, that the user owncast wasn't allowed to access the whole path. I had to 755 /var - then it worked fine.

Oh okay, didn't know that. Thanks !

2021-01-14 03:47 UTC, gabek commented
Hi there, what's the status of this?  Also, is the scope of this discussing reverse proxies as well, or just systemd?  I saw proxies mentioned above.  If it's not a part of this, can a new PR be opened with the proxy changes so we can get those?  The proxy documentation is more important at this point.

https://owncast.rocket.chat/channel/general?msg=3akEgMSeomnJyX6o6

2021-01-14 07:38 UTC, jeyemwey commented
I agree, if the content/scripts of this PR are correct, we should merge it and care about nitpicks later.

2021-01-27 07:28 UTC, gabek commented
@SkYNewZ Hey there!  This PR is a draft, what were you thinking about the next steps with this?

2021-01-28 07:38 UTC, jeyemwey commented
Has this been integrated with d32814f477e256fce1270235d62baad3469c076e ? I would be fine closing this issue then.

2021-01-28 07:57 UTC, gabek commented
I wanted to give @SkYNewZ a chance to finalize it, since the PR is just a draft.  I did copy what he had, but I understand he didn't get to finishing it yet.

2021-01-29 14:55 UTC, SkYNewZ commented
Hello ! Sorry for the response time, I'm not very active at the moment. Concerning this PR, I think I'm done. I saw that you accepted my proposal and I am delighted! We can close this now.

2021-01-29 14:55 UTC, closed without merging