css tweaks
owncast/owncast.github.io pull request #27
Opened 2020-12-30 08:18 UTC by gingervitis

I added some color and spacing tweaks to mostly Heading elements to make the sections on each page stand out a bit more, and might assist people in noticing content that is available on the site.

2020-12-30 08:44 UTC, gabek commented on content/posts/_index.md
> +All the miporatnat stuff
```suggestion
```

2020-12-30 20:50 UTC, jeyemwey requested changes

2020-12-30 20:50 UTC, jeyemwey commented on assets/_custom.scss
> +}
This breaks the mobile navigation:

![grafik](https://user-images.githubusercontent.com/2796271/103380158-51318500-4ae8-11eb-9011-527da40d6671.png)

Maybe, add a `padding-top: 1rem` with a media query?

2021-01-01 05:33 UTC, gingervitis commented on assets/_custom.scss
> +}
updated!

2021-01-02 12:21 UTC, jeyemwey approved these changes

2021-01-02 12:22 UTC, jeyemwey commented
Looks good to me, if @gabek is fine with it, I'd merge this PR.

2021-01-02 18:55 UTC, gabek commented
Looks good to me!

2021-01-02 18:56 UTC, merged