minio S3 documentation
owncast/owncast.github.io pull request #32
Opened 2021-01-08 16:13 UTC by felix-engelmann

To have full control over your stream, you may self host the video chunks on MinIO.

2021-01-09 00:48 UTC, gabek commented
Nice!

2021-01-09 10:19 UTC, jeyemwey requested changes
Hi, thank you for your awesome contribution to our documentation. :) There are few things that I’d like to change before merging, but then I’m good to go :)

2021-01-09 10:19 UTC, jeyemwey commented on content/docs/S3.md
> +Create a bucket, e.g. with the [minio client](https://docs.min.io/docs/minio-client-complete-guide.html) by
```suggestion
Create a bucket, e.g. with the [MinIO client](https://docs.min.io/docs/minio-client-complete-guide.html) by
```

Fix typo

2021-01-09 10:19 UTC, jeyemwey commented on content/docs/S3.md
> +Make sure to allow access to the buckets file from your owncast domain.
Can you link to some documentation? I’ve seen many people having problems with CORS in the Owncast discussions, so a link to a tutorial or documentation would be great.

2021-01-09 10:19 UTC, jeyemwey commented on content/docs/S3.md
> +* add an alias `mc alias set <ALIAS> <YOUR-S3-ENDPOINT> [YOUR-ACCESS-KEY] [YOUR-SECRET-KEY]`
Who defines `[YOUR-ACCESS-KEY]` and `[YOUR-SECRET-KEY]`? Is that a random passphrase that the user can enter and has to generate somewhere else?

2021-01-09 13:17 UTC, felix-engelmann commented on content/docs/S3.md
> +* add an alias `mc alias set <ALIAS> <YOUR-S3-ENDPOINT> [YOUR-ACCESS-KEY] [YOUR-SECRET-KEY]`
I'm not sure if I should explain the setup of MinIO itself too. Therefore I referenced an example docker-compose

2021-01-09 13:17 UTC, felix-engelmann commented on content/docs/S3.md
> +Make sure to allow access to the buckets file from your owncast domain.
As it depends on the reverse proxy in front of MinIO, I explained it for traefik.

2021-01-12 23:10 UTC, gabek commented on content/docs/S3.md
> +* add an alias `mc alias set <ALIAS> <YOUR-S3-ENDPOINT> [YOUR-ACCESS-KEY] [YOUR-SECRET-KEY]`
I think this is good how it is.  If you use MinIO then you understand those values and how to use them.  If you don't already use MinIO then this documentation probably isn't for you.

2021-01-13 07:01 UTC, jeyemwey commented on content/docs/S3.md
> +If you want to host the video segments on a self hosted S3 compatible [MinIO](https://min.io/) server, you get even more control over your data. A docker-compose deployment example is available in th
I'm not sure if the normal docker compose should have a minion host. That would be another thing to test against, while this is just part of the documentation.

2021-01-13 07:10 UTC, gabek commented on content/docs/S3.md
> +For details, c.f. the [documentation](https://doc.traefik.io/traefik/middlewares/headers/#cors-headers), respective of the reverse proxy you use.
I'd vote just to stop at saying "Make sure to allow access to the buckets file from your owncast domain".  The rest is a lot of detail, and if people don't use traefik then it's not terribly useful anyway.

2021-01-13 07:10 UTC, gabek commented on content/docs/S3.md
> +  servingEndpoint: https://<s3-storage.your.org>/stream
`servingEndpoint` is optional and only required if the hostname you want to serve from is different than the rl that the S3 provider returns.  I'm not sure if this is the case with MinIO or not.

2021-01-13 09:11 UTC, felix-engelmann commented on content/docs/S3.md
> +For details, c.f. the [documentation](https://doc.traefik.io/traefik/middlewares/headers/#cors-headers), respective of the reverse proxy you use.
@jeyemwey maybe documenting the plain http headers migt be better?

2021-01-13 09:13 UTC, felix-engelmann commented on content/docs/S3.md
> +  servingEndpoint: https://<s3-storage.your.org>/stream
As minio does not support DNS subdomain style bucket addresses, we need the servingEndpoint to append the bucket name in the path.

2021-01-15 23:05 UTC, jeyemwey commented
Looks good to me, thank you for your help and contributions!

2021-01-15 23:06 UTC, jeyemwey approved these changes

2021-01-15 23:06 UTC, merged